# Generated by Django 3.2.7 on 2021-09-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darasa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darasa',
            old_name='linenous',
            new_name='linenos',
        ),
    ]
